# Generated by Django 5.2.6 on 2025-09-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trailer_file',
            field=models.FileField(blank=True, upload_to='trailers/'),
        ),
    ]
