# Generated by Django 5.2.6 on 2025-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_course_trailer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='editor_pick_weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Priorité d’affichage (0 = auto).'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_editor_pick',
            field=models.BooleanField(default=False, help_text='Prochain coup de cœur (rail éditorial).'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_full_pack',
            field=models.BooleanField(default=False, help_text="Afficher dans la rangée 'Packs complets'."),
        ),
        migrations.AddField(
            model_name='course',
            name='pack_weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Priorité d’affichage (0 = auto).'),
        ),
        migrations.AddField(
            model_name='course',
            name='top10_rank',
            field=models.PositiveSmallIntegerField(blank=True, help_text="1..10 pour forcer l’ordre du 'Top 10'.", null=True),
        ),
    ]
