# Generated by Django 5.2.6 on 2025-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_course_editor_pick_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trailer_cf_playback_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='trailer_cf_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='trailer_cf_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
