# Generated by Django 5.2.6 on 2025-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_documentdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cf_playback_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cf_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cf_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
