# Generated by Django 5.2.6 on 2025-09-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
